### PR TITLE
Improve usage of source element

### PR DESCRIPTION
**Pull request by chaenu**
- Introduce a more flexible and general way to define the <source>
  elements, based on the data
- Recommend usage of srcset and sizes attribute as default, not usage
  via media attribute (let browsers do their job, not define strictly
  which image they must use)
- Add documentation when and how to use which type
- Add possibility to use new image formats like webp

### CODE REVIEW

**Comment by Sebastian-Fitzner** [comment]
Looks pretty good. We use a similar version in our project too. 

Would be nice if you can update the hyphenated words to camelcase. 

Furthermore I like to add data-src for lazyloading as option. 

What do you think?

**Comment by Sebastian-Fitzner** [comment]
The documentation should be placed in the readme file. And we need to keep Json because of compatibility to assemble.

**Comment by chaenu** [comment]
Alright, done. Should the two readme files differ? They currently both contain the documentation of the configuration options.

And yes, I guess lazyloading should be the next feature. We're looking forward to add it in our project in the next few days, so we'll probably add another pull request.

**Comment by Sebastian-Fitzner** [comment]
We can delete the readme file in the usage folder ...

**Pull request merged**
